language: node_js

node_js:
  - "10"
  - "9"
  - "8"
  - "6"

env:
  - GULP_VERSION=3.6.0
  - GULP_VERSION=^3.6
  - GULP_VERSION=^4.0

sudo: false

before_script:
  - npm install -g gulp@$GULP_VERSION

script: gulp
